version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  sync-bridge:
    build:
      context: .
    ports:
      - 3500:3500
    environment:
      - PORT=3500
      - MULTICHAIN_HOST=host.docker.internal
      - MULTICHAIN_PORT=8570
      - MULTICHAIN_USER=multichainrpc
      - MULTICHAIN_PASSWORD=password
      - READ_FROM_CHAIN=false
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_HOST=eventstore
      - EVENT_STORE_PORT=1113
    networks:
      - backend
