version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  sync-bridge:
    build:
      context: .
    environment:
      - PORT=3500
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=sync
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_HOST=eventstore
      - EVENT_STORE_PORT=1113
    networks:
      - backend
