version: '3'

services:

  event-bridge:
    build:
      context: .
    ports:
      - 3500:3500
    environment:
      - PORT=3500
      - EVENT_STORE_PORT=1113
      - EVENT_STORE_HOST=eventstore
    networks:
      - sensrnet-registry-backend_backend

networks:
  sensrnet-registry-backend_backend:
    external: true
