version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  sync-bridge:
    build:
      context: .
    environment:
      - PORT=3500
      - MULTICHAIN_HOST=192.168.178.23
      - MULTICHAIN_USER=multichainrpc
      - MULTICHAIN_PORT=8002
      - MULTICHAIN_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_HOST=eventstore
      - EVENT_STORE_PORT=1113
    networks:
      - backend
