apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-bridge
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sync-bridge
        image: sensrnetnl/sync-bridge:latest
        ports:
        - name: http
          containerPort: 3500
        env:
        - name: EVENT_STORE_HOST
          value: eventstore-cluster
        - name: EVENT_STORE_PORT
          value: eventstore-tcp
        - name: MULTICHAIN_HOST
          value: multichain-service.multichain.svc.cluster.local
        - name: MULTICHAIN_USER
          valueFrom:
              secretKeyRef:
                name: json-rpc-credentials
                key: username
        - name: MULTICHAIN_PASSWORD
          valueFrom:
              secretKeyRef:
                name: json-rpc-credentials
                key: password
        - name: MULTICHAIN_PORT
          value: "8570"
        - name: MONGO_DATABASE
          value: sensrnet
        - name: MONGO_HOST
          value: mongo
        - name: MONGO_PORT
          value: mongo
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5