version: '3'

services:

  sync-bridge:
    build:
      context: .
    ports:
      - 3500:3500
    environment:
      - PORT=3500
      - NODE_ID=node_1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_PORT=1113
      - EVENT_STORE_HOST=eventstore
    networks:
      - bridge

networks:
  bridge:
    external:
      name: backend_backend
