version: '3'

networks:
  bridge:
    external:
      name: backend

services:

  sync-bridge:
    build:
      context: .
    ports:
      - 3500:3500
    environment:
      - PORT=3500
      - NODE_ID=node_1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=sensrnet
      - EVENT_STORE_PORT=1113
      - EVENT_STORE_HOST=eventstore
    volumes:
      - ./connection-org1.json:/app/connection-org1.json
    networks:
      - bridge
